name: "OwlCraft"
version: ${project.version}
main: net.owlcraft.core.OwlCraft

api-version: "1.20"
description: OwlCraft Plugin
authors: [ "gabehxd", "SunResearchInstitute" ]

commands:
  glyph:
    description: "Glyph command main menu"
    permission: owlcraft.commands.glyph

permissions:
  owlcraft.commands.glyph:
    description: "Allows access to glyph command"
    default: op
  owlcraft.commands.glyph.give:
    description: "Allows you to give glyphs"
    default: op